url: http://aleksandrov.ws
name: aleksandrov.ws
markdown: redcarpet
pygments: true
permalink: pretty

theme:
  name: Evgeny Aleksandrov
  whoyouare: iOS developer
  email: evgeny@aleksandrov.ws
  
  social:
    github: ealeksandrov
    bitbucket: ealeks
    skype: evgeny-aleksandrov
    stackexchange: 447136
    stackoverflow: 840588
    twitter: ealeksandrov
    facebook: evgeny.aleksandrov.14
    vk: 8475152
    linkedin: evgeny-aleksandrov/62/680/956
    gplus: 106054359575752422060

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-46367444-1
  google_analytics_URL: aleksandrov.ws
